version: '3'
services: 
  frontend:
    container_name: isdl-sentinel-frontend
    build: ./frontend
    env_file:
      - .env
    tty: true
    stdin_open: true
    ports:
      - 4000:4000
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c 'yarn install && yarn start'
  backend:
    container_name: isdl-sentinel-backend
    build: ./backend
    env_file:
      - .env
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./backend:/go/src/backend
  database:
    image: mysql:8.0
    container_name: isdl-sentinel-database
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        TZ: ${TZ}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    tty: true
    stdin_open: true
    volumes:
        - ./database/data:/var/lib/mysql
        - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./database/sqls:/docker-entrypoint-initdb.d
    ports:
        - 3306:3306

