version: '3'
services: 
  frontend:
    container_name: isdl-sentinel-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: ${ENV_TYPE:-dev}
      args:
        - ENV_TYPE=${ENV_TYPE:-dev}
    environment:
      - REACT_APP_BACKEND_ENDPOINT=${BACKEND_ENDPOINT}
      - ENV_TYPE=${ENV_TYPE:-dev}
    env_file:
      - .env.${ENV_TYPE:-dev}
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 4000:4000
    
  backend:
    container_name: isdl-sentinel-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${ENV_TYPE:-dev}
      args:
        - ENV_TYPE=${ENV_TYPE:-dev}
    env_file:
      - .env.${ENV_TYPE:-dev}
    environment:
      - ENV_TYPE=${ENV_TYPE:-dev}
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/go/src/app
    ports:
      - 3000:3000

  database:
    image: mysql:8.0
    container_name: ${MYSQL_HOSTNAME}
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        TZ: ${TZ}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    tty: true
    stdin_open: true
    volumes:
        - ./database/data_${ENV_TYPE:-dev}:/var/lib/mysql
        - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./database/sqls_${ENV_TYPE:-dev}:/docker-entrypoint-initdb.d
    ports:
        - 3306:3306