/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type GetUserById200Response struct {

	UserId int32 `json:"user_id,omitempty"`

	UserName string `json:"user_name,omitempty"`

	MailAddress string `json:"mail_address,omitempty"`

	NumberOfCoin int32 `json:"number_of_coin,omitempty"`

	AttendanceDays int32 `json:"attendance_days,omitempty"`

	StayTime string `json:"stay_time,omitempty"`

	Status string `json:"status,omitempty"`

	Place string `json:"place,omitempty"`

	Grade string `json:"grade,omitempty"`

	AvatarId int32 `json:"avatar_id,omitempty"`

	AvatarImgPath string `json:"avatar_img_path,omitempty"`

	AvatarList []GetUserById200ResponseAvatarListInner `json:"avatar_list,omitempty"`
}

