/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type GetAttendeesList200ResponseInner struct {

	UserId int32 `json:"user_id"`

	UserName string `json:"user_name"`

	EnteredAt string `json:"entered_at"`

	Purpose string `json:"purpose"`

	Status string `json:"status"`

	Place string `json:"place"`

	Grade string `json:"grade"`

	AvatarId int32 `json:"avatar_id"`

	AvatarImgPath string `json:"avatar_img_path"`
}

