/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type PostSignInRequest struct {

	MailAddress string `json:"mail_address,omitempty"`

	Password string `json:"password,omitempty"`
}

