/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type GetUserById200ResponseAvatarListInner struct {

	AvatarId int32 `json:"avatar_id"`

	ImgPath string `json:"img_path"`
}

