/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type AccessHistoryInnerLeaving struct {

	UserId int32 `json:"user_id,omitempty"`

	UserName string `json:"user_name,omitempty"`

	AvatarId int32 `json:"avatar_id,omitempty"`

	AvatarImgPath string `json:"avatar_img_path,omitempty"`

	LeftAt string `json:"left_at,omitempty"`
}

