/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type GetLabAssistantMember200ResponseInner struct {

	UserId int32 `json:"user_id"`

	UserName string `json:"user_name"`

	AvatarId int32 `json:"avatar_id"`

	AvatarImgPath string `json:"avatar_img_path"`

	LastShiftDate string `json:"last_shift_date"`

	Count int32 `json:"count"`
}

