/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type AttendeesListInner struct {

	UserId int32 `json:"user_id,omitempty"`

	UserName string `json:"user_name,omitempty"`

	EnteredAt string `json:"entered_at,omitempty"`

	Purpose string `json:"purpose,omitempty"`

	Status string `json:"status,omitempty"`

	Place string `json:"place,omitempty"`

	Grade string `json:"grade,omitempty"`

	Avatar string `json:"avatar,omitempty"`
}

