/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type AccessHistoryInner struct {

	Date string `json:"date,omitempty"`

	Entering AccessHistoryInnerEntering `json:"entering,omitempty"`

	Leaving AccessHistoryInnerLeaving `json:"leaving,omitempty"`
}

