/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type UserInformationAvatarListInner struct {

	AvatarId int32 `json:"avatar_id,omitempty"`

	AvatarName string `json:"avatar_name,omitempty"`

	Rarity int32 `json:"rarity,omitempty"`

	ImgPath string `json:"img_path,omitempty"`
}

