/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type UserListInner struct {

	UserId int32 `json:"user_id,omitempty"`

	Name string `json:"name,omitempty"`

	MailAddress string `json:"mail_address,omitempty"`
}

