/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type GetLabAsistantMember200ResponseInner struct {

	UserId int32 `json:"user_id"`

	UserName string `json:"user_name"`
}

