/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type RankingListInner struct {

	UserId int32 `json:"user_id,omitempty"`

	UserName string `json:"user_name,omitempty"`

	StayTime string `json:"stay_time,omitempty"`

	Grade string `json:"grade,omitempty"`

	Avatar string `json:"avatar,omitempty"`
}

