/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type PostUserInformationRequest struct {

	Name string `json:"name"`

	AuthUserName string `json:"auth_user_name"`

	MailAddress string `json:"mail_address"`

	Password string `json:"password"`

	GradeName string `json:"grade_name"`
}

