/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type GetAccessHistory200ResponseInner struct {

	Date string `json:"date"`

	Entering GetAccessHistory200ResponseInnerEntering `json:"entering"`

	Leaving GetAccessHistory200ResponseInnerLeaving `json:"leaving"`
}

