/*
 * ISDL Sentinel API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type GetLabAsistantSchedule200ResponseInner struct {

	UserName string `json:"user_name"`

	ShiftDate string `json:"shift_date"`
}

