/* tslint:disable */
/* eslint-disable */
/**
 * ISDL Sentinel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Avatar
 */
export interface Avatar {
    /**
     * 
     * @type {number}
     * @memberof Avatar
     */
    'user_id': number;
    /**
     * 
     * @type {number}
     * @memberof Avatar
     */
    'avatar_id': number;
}
/**
 * 
 * @export
 * @interface GetAccessHistory200ResponseInner
 */
export interface GetAccessHistory200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof GetAccessHistory200ResponseInner
     */
    'date': string;
    /**
     * 
     * @type {GetAccessHistory200ResponseInnerEntering}
     * @memberof GetAccessHistory200ResponseInner
     */
    'entering': GetAccessHistory200ResponseInnerEntering;
    /**
     * 
     * @type {GetAccessHistory200ResponseInnerLeaving}
     * @memberof GetAccessHistory200ResponseInner
     */
    'leaving': GetAccessHistory200ResponseInnerLeaving;
}
/**
 * 
 * @export
 * @interface GetAccessHistory200ResponseInnerEntering
 */
export interface GetAccessHistory200ResponseInnerEntering {
    /**
     * 
     * @type {number}
     * @memberof GetAccessHistory200ResponseInnerEntering
     */
    'user_id': number;
    /**
     * 
     * @type {string}
     * @memberof GetAccessHistory200ResponseInnerEntering
     */
    'user_name': string;
    /**
     * 
     * @type {number}
     * @memberof GetAccessHistory200ResponseInnerEntering
     */
    'avatar_id': number;
    /**
     * 
     * @type {string}
     * @memberof GetAccessHistory200ResponseInnerEntering
     */
    'avatar_img_path': string;
    /**
     * 
     * @type {string}
     * @memberof GetAccessHistory200ResponseInnerEntering
     */
    'entered_at': string;
}
/**
 * 
 * @export
 * @interface GetAccessHistory200ResponseInnerLeaving
 */
export interface GetAccessHistory200ResponseInnerLeaving {
    /**
     * 
     * @type {number}
     * @memberof GetAccessHistory200ResponseInnerLeaving
     */
    'user_id': number;
    /**
     * 
     * @type {string}
     * @memberof GetAccessHistory200ResponseInnerLeaving
     */
    'user_name': string;
    /**
     * 
     * @type {number}
     * @memberof GetAccessHistory200ResponseInnerLeaving
     */
    'avatar_id': number;
    /**
     * 
     * @type {string}
     * @memberof GetAccessHistory200ResponseInnerLeaving
     */
    'avatar_img_path': string;
    /**
     * 
     * @type {string}
     * @memberof GetAccessHistory200ResponseInnerLeaving
     */
    'left_at': string;
}
/**
 * 
 * @export
 * @interface GetAttendeesList200ResponseInner
 */
export interface GetAttendeesList200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof GetAttendeesList200ResponseInner
     */
    'user_id': number;
    /**
     * 
     * @type {string}
     * @memberof GetAttendeesList200ResponseInner
     */
    'user_name': string;
    /**
     * 
     * @type {string}
     * @memberof GetAttendeesList200ResponseInner
     */
    'entered_at': string;
    /**
     * 
     * @type {string}
     * @memberof GetAttendeesList200ResponseInner
     */
    'purpose': string;
    /**
     * 
     * @type {string}
     * @memberof GetAttendeesList200ResponseInner
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof GetAttendeesList200ResponseInner
     */
    'place': string;
    /**
     * 
     * @type {string}
     * @memberof GetAttendeesList200ResponseInner
     */
    'grade': string;
    /**
     * 
     * @type {number}
     * @memberof GetAttendeesList200ResponseInner
     */
    'avatar_id': number;
    /**
     * 
     * @type {string}
     * @memberof GetAttendeesList200ResponseInner
     */
    'avatar_img_path': string;
}
/**
 * 
 * @export
 * @interface GetRanking200ResponseInner
 */
export interface GetRanking200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof GetRanking200ResponseInner
     */
    'user_id': number;
    /**
     * 
     * @type {string}
     * @memberof GetRanking200ResponseInner
     */
    'user_name': string;
    /**
     * 
     * @type {number}
     * @memberof GetRanking200ResponseInner
     */
    'attendance_days': number;
    /**
     * 
     * @type {string}
     * @memberof GetRanking200ResponseInner
     */
    'stay_time': string;
    /**
     * 
     * @type {string}
     * @memberof GetRanking200ResponseInner
     */
    'grade': string;
    /**
     * 
     * @type {number}
     * @memberof GetRanking200ResponseInner
     */
    'avatar_id': number;
    /**
     * 
     * @type {string}
     * @memberof GetRanking200ResponseInner
     */
    'avatar_img_path': string;
}
/**
 * 
 * @export
 * @interface GetUserById200Response
 */
export interface GetUserById200Response {
    /**
     * 
     * @type {number}
     * @memberof GetUserById200Response
     */
    'user_id': number;
    /**
     * 
     * @type {string}
     * @memberof GetUserById200Response
     */
    'user_name': string;
    /**
     * 
     * @type {string}
     * @memberof GetUserById200Response
     */
    'mail_address': string;
    /**
     * 
     * @type {number}
     * @memberof GetUserById200Response
     */
    'number_of_coin': number;
    /**
     * 
     * @type {number}
     * @memberof GetUserById200Response
     */
    'attendance_days': number;
    /**
     * 
     * @type {string}
     * @memberof GetUserById200Response
     */
    'stay_time': string;
    /**
     * 
     * @type {string}
     * @memberof GetUserById200Response
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof GetUserById200Response
     */
    'place': string;
    /**
     * 
     * @type {string}
     * @memberof GetUserById200Response
     */
    'grade': string;
    /**
     * 
     * @type {number}
     * @memberof GetUserById200Response
     */
    'avatar_id': number;
    /**
     * 
     * @type {string}
     * @memberof GetUserById200Response
     */
    'avatar_img_path': string;
    /**
     * 
     * @type {Array<GetUserById200ResponseAvatarListInner>}
     * @memberof GetUserById200Response
     */
    'avatar_list': Array<GetUserById200ResponseAvatarListInner>;
}
/**
 * 
 * @export
 * @interface GetUserById200ResponseAvatarListInner
 */
export interface GetUserById200ResponseAvatarListInner {
    /**
     * 
     * @type {number}
     * @memberof GetUserById200ResponseAvatarListInner
     */
    'avatar_id': number;
    /**
     * 
     * @type {string}
     * @memberof GetUserById200ResponseAvatarListInner
     */
    'avatar_name': string;
    /**
     * 
     * @type {number}
     * @memberof GetUserById200ResponseAvatarListInner
     */
    'rarity': number;
    /**
     * 
     * @type {string}
     * @memberof GetUserById200ResponseAvatarListInner
     */
    'img_path': string;
}
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {number}
     * @memberof ModelError
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface PostSignIn200Response
 */
export interface PostSignIn200Response {
    /**
     * 
     * @type {number}
     * @memberof PostSignIn200Response
     */
    'user_id': number;
    /**
     * 
     * @type {string}
     * @memberof PostSignIn200Response
     */
    'user_name': string;
    /**
     * 
     * @type {number}
     * @memberof PostSignIn200Response
     */
    'avatar_id': number;
    /**
     * 
     * @type {string}
     * @memberof PostSignIn200Response
     */
    'avatar_img_path': string;
}
/**
 * 
 * @export
 * @interface PostSignInRequest
 */
export interface PostSignInRequest {
    /**
     * 
     * @type {string}
     * @memberof PostSignInRequest
     */
    'mail_address': string;
    /**
     * 
     * @type {string}
     * @memberof PostSignInRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface PostUserInformationRequest
 */
export interface PostUserInformationRequest {
    /**
     * 
     * @type {string}
     * @memberof PostUserInformationRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof PostUserInformationRequest
     */
    'mail_address': string;
    /**
     * 
     * @type {string}
     * @memberof PostUserInformationRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface PutChangePasswordRequest
 */
export interface PutChangePasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof PutChangePasswordRequest
     */
    'mail_address': string;
    /**
     * 
     * @type {string}
     * @memberof PutChangePasswordRequest
     */
    'before_password': string;
    /**
     * 
     * @type {string}
     * @memberof PutChangePasswordRequest
     */
    'after_password': string;
}
/**
 * 
 * @export
 * @interface Status
 */
export interface Status {
    /**
     * 
     * @type {number}
     * @memberof Status
     */
    'user_id': number;
    /**
     * 
     * @type {string}
     * @memberof Status
     */
    'status': string;
}

/**
 * GetAccessHistoryApi - axios parameter creator
 * @export
 */
export const GetAccessHistoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get access history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccessHistory: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/access-history`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GetAccessHistoryApi - functional programming interface
 * @export
 */
export const GetAccessHistoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GetAccessHistoryApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get access history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAccessHistory(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetAccessHistory200ResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAccessHistory(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GetAccessHistoryApi.getAccessHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GetAccessHistoryApi - factory interface
 * @export
 */
export const GetAccessHistoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GetAccessHistoryApiFp(configuration)
    return {
        /**
         * 
         * @summary Get access history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccessHistory(options?: any): AxiosPromise<Array<GetAccessHistory200ResponseInner>> {
            return localVarFp.getAccessHistory(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GetAccessHistoryApi - object-oriented interface
 * @export
 * @class GetAccessHistoryApi
 * @extends {BaseAPI}
 */
export class GetAccessHistoryApi extends BaseAPI {
    /**
     * 
     * @summary Get access history
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GetAccessHistoryApi
     */
    public getAccessHistory(options?: RawAxiosRequestConfig) {
        return GetAccessHistoryApiFp(this.configuration).getAccessHistory(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * GetAttendeesListApi - axios parameter creator
 * @export
 */
export const GetAttendeesListApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get attendees list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttendeesList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/attendees-list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GetAttendeesListApi - functional programming interface
 * @export
 */
export const GetAttendeesListApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GetAttendeesListApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get attendees list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAttendeesList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetAttendeesList200ResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAttendeesList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GetAttendeesListApi.getAttendeesList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GetAttendeesListApi - factory interface
 * @export
 */
export const GetAttendeesListApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GetAttendeesListApiFp(configuration)
    return {
        /**
         * 
         * @summary Get attendees list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttendeesList(options?: any): AxiosPromise<Array<GetAttendeesList200ResponseInner>> {
            return localVarFp.getAttendeesList(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GetAttendeesListApi - object-oriented interface
 * @export
 * @class GetAttendeesListApi
 * @extends {BaseAPI}
 */
export class GetAttendeesListApi extends BaseAPI {
    /**
     * 
     * @summary Get attendees list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GetAttendeesListApi
     */
    public getAttendeesList(options?: RawAxiosRequestConfig) {
        return GetAttendeesListApiFp(this.configuration).getAttendeesList(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * GetAvatarByIdApi - axios parameter creator
 * @export
 */
export const GetAvatarByIdApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get an avatar by ID
         * @param {number} count 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAvatarById: async (count: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'count' is not null or undefined
            assertParamExists('getAvatarById', 'count', count)
            const localVarPath = `/avatar/{count}`
                .replace(`{${"count"}}`, encodeURIComponent(String(count)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GetAvatarByIdApi - functional programming interface
 * @export
 */
export const GetAvatarByIdApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GetAvatarByIdApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get an avatar by ID
         * @param {number} count 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAvatarById(count: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetUserById200ResponseAvatarListInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAvatarById(count, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GetAvatarByIdApi.getAvatarById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GetAvatarByIdApi - factory interface
 * @export
 */
export const GetAvatarByIdApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GetAvatarByIdApiFp(configuration)
    return {
        /**
         * 
         * @summary Get an avatar by ID
         * @param {number} count 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAvatarById(count: number, options?: any): AxiosPromise<Array<GetUserById200ResponseAvatarListInner>> {
            return localVarFp.getAvatarById(count, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GetAvatarByIdApi - object-oriented interface
 * @export
 * @class GetAvatarByIdApi
 * @extends {BaseAPI}
 */
export class GetAvatarByIdApi extends BaseAPI {
    /**
     * 
     * @summary Get an avatar by ID
     * @param {number} count 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GetAvatarByIdApi
     */
    public getAvatarById(count: number, options?: RawAxiosRequestConfig) {
        return GetAvatarByIdApiFp(this.configuration).getAvatarById(count, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * GetAvatarListApi - axios parameter creator
 * @export
 */
export const GetAvatarListApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get avatar list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAvatarList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/avatar-list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GetAvatarListApi - functional programming interface
 * @export
 */
export const GetAvatarListApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GetAvatarListApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get avatar list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAvatarList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetUserById200ResponseAvatarListInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAvatarList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GetAvatarListApi.getAvatarList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GetAvatarListApi - factory interface
 * @export
 */
export const GetAvatarListApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GetAvatarListApiFp(configuration)
    return {
        /**
         * 
         * @summary Get avatar list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAvatarList(options?: any): AxiosPromise<Array<GetUserById200ResponseAvatarListInner>> {
            return localVarFp.getAvatarList(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GetAvatarListApi - object-oriented interface
 * @export
 * @class GetAvatarListApi
 * @extends {BaseAPI}
 */
export class GetAvatarListApi extends BaseAPI {
    /**
     * 
     * @summary Get avatar list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GetAvatarListApi
     */
    public getAvatarList(options?: RawAxiosRequestConfig) {
        return GetAvatarListApiFp(this.configuration).getAvatarList(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * GetRankingApi - axios parameter creator
 * @export
 */
export const GetRankingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get ranking
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRanking: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ranking`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GetRankingApi - functional programming interface
 * @export
 */
export const GetRankingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GetRankingApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get ranking
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRanking(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetRanking200ResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRanking(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GetRankingApi.getRanking']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GetRankingApi - factory interface
 * @export
 */
export const GetRankingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GetRankingApiFp(configuration)
    return {
        /**
         * 
         * @summary Get ranking
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRanking(options?: any): AxiosPromise<Array<GetRanking200ResponseInner>> {
            return localVarFp.getRanking(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GetRankingApi - object-oriented interface
 * @export
 * @class GetRankingApi
 * @extends {BaseAPI}
 */
export class GetRankingApi extends BaseAPI {
    /**
     * 
     * @summary Get ranking
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GetRankingApi
     */
    public getRanking(options?: RawAxiosRequestConfig) {
        return GetRankingApiFp(this.configuration).getRanking(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * GetUserByIdApi - axios parameter creator
 * @export
 */
export const GetUserByIdApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a user by ID
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserById: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserById', 'userId', userId)
            const localVarPath = `/users/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GetUserByIdApi - functional programming interface
 * @export
 */
export const GetUserByIdApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GetUserByIdApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get a user by ID
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserById(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserById200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserById(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GetUserByIdApi.getUserById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GetUserByIdApi - factory interface
 * @export
 */
export const GetUserByIdApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GetUserByIdApiFp(configuration)
    return {
        /**
         * 
         * @summary Get a user by ID
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserById(userId: number, options?: any): AxiosPromise<GetUserById200Response> {
            return localVarFp.getUserById(userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GetUserByIdApi - object-oriented interface
 * @export
 * @class GetUserByIdApi
 * @extends {BaseAPI}
 */
export class GetUserByIdApi extends BaseAPI {
    /**
     * 
     * @summary Get a user by ID
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GetUserByIdApi
     */
    public getUserById(userId: number, options?: RawAxiosRequestConfig) {
        return GetUserByIdApiFp(this.configuration).getUserById(userId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PostSignInApi - axios parameter creator
 * @export
 */
export const PostSignInApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Sign in
         * @param {PostSignInRequest} [postSignInRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postSignIn: async (postSignInRequest?: PostSignInRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/sign-in`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postSignInRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PostSignInApi - functional programming interface
 * @export
 */
export const PostSignInApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PostSignInApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Sign in
         * @param {PostSignInRequest} [postSignInRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postSignIn(postSignInRequest?: PostSignInRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostSignIn200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postSignIn(postSignInRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PostSignInApi.postSignIn']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PostSignInApi - factory interface
 * @export
 */
export const PostSignInApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PostSignInApiFp(configuration)
    return {
        /**
         * 
         * @summary Sign in
         * @param {PostSignInRequest} [postSignInRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postSignIn(postSignInRequest?: PostSignInRequest, options?: any): AxiosPromise<PostSignIn200Response> {
            return localVarFp.postSignIn(postSignInRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PostSignInApi - object-oriented interface
 * @export
 * @class PostSignInApi
 * @extends {BaseAPI}
 */
export class PostSignInApi extends BaseAPI {
    /**
     * 
     * @summary Sign in
     * @param {PostSignInRequest} [postSignInRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostSignInApi
     */
    public postSignIn(postSignInRequest?: PostSignInRequest, options?: RawAxiosRequestConfig) {
        return PostSignInApiFp(this.configuration).postSignIn(postSignInRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PostUserInformationApi - axios parameter creator
 * @export
 */
export const PostUserInformationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create user information
         * @param {PostUserInformationRequest} [postUserInformationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserInformation: async (postUserInformationRequest?: PostUserInformationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/sign-up`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postUserInformationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PostUserInformationApi - functional programming interface
 * @export
 */
export const PostUserInformationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PostUserInformationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create user information
         * @param {PostUserInformationRequest} [postUserInformationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUserInformation(postUserInformationRequest?: PostUserInformationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostSignIn200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postUserInformation(postUserInformationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PostUserInformationApi.postUserInformation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PostUserInformationApi - factory interface
 * @export
 */
export const PostUserInformationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PostUserInformationApiFp(configuration)
    return {
        /**
         * 
         * @summary Create user information
         * @param {PostUserInformationRequest} [postUserInformationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserInformation(postUserInformationRequest?: PostUserInformationRequest, options?: any): AxiosPromise<PostSignIn200Response> {
            return localVarFp.postUserInformation(postUserInformationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PostUserInformationApi - object-oriented interface
 * @export
 * @class PostUserInformationApi
 * @extends {BaseAPI}
 */
export class PostUserInformationApi extends BaseAPI {
    /**
     * 
     * @summary Create user information
     * @param {PostUserInformationRequest} [postUserInformationRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostUserInformationApi
     */
    public postUserInformation(postUserInformationRequest?: PostUserInformationRequest, options?: RawAxiosRequestConfig) {
        return PostUserInformationApiFp(this.configuration).postUserInformation(postUserInformationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PutAvatarApi - axios parameter creator
 * @export
 */
export const PutAvatarApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary update avatar
         * @param {Avatar} avatar request body of update avatar
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putAvatar: async (avatar: Avatar, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'avatar' is not null or undefined
            assertParamExists('putAvatar', 'avatar', avatar)
            const localVarPath = `/avatar`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(avatar, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PutAvatarApi - functional programming interface
 * @export
 */
export const PutAvatarApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PutAvatarApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary update avatar
         * @param {Avatar} avatar request body of update avatar
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putAvatar(avatar: Avatar, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Avatar>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putAvatar(avatar, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PutAvatarApi.putAvatar']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PutAvatarApi - factory interface
 * @export
 */
export const PutAvatarApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PutAvatarApiFp(configuration)
    return {
        /**
         * 
         * @summary update avatar
         * @param {Avatar} avatar request body of update avatar
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putAvatar(avatar: Avatar, options?: any): AxiosPromise<Avatar> {
            return localVarFp.putAvatar(avatar, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PutAvatarApi - object-oriented interface
 * @export
 * @class PutAvatarApi
 * @extends {BaseAPI}
 */
export class PutAvatarApi extends BaseAPI {
    /**
     * 
     * @summary update avatar
     * @param {Avatar} avatar request body of update avatar
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PutAvatarApi
     */
    public putAvatar(avatar: Avatar, options?: RawAxiosRequestConfig) {
        return PutAvatarApiFp(this.configuration).putAvatar(avatar, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PutChangePasswordApi - axios parameter creator
 * @export
 */
export const PutChangePasswordApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary change password
         * @param {PutChangePasswordRequest} [putChangePasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putChangePassword: async (putChangePasswordRequest?: PutChangePasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(putChangePasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PutChangePasswordApi - functional programming interface
 * @export
 */
export const PutChangePasswordApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PutChangePasswordApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary change password
         * @param {PutChangePasswordRequest} [putChangePasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putChangePassword(putChangePasswordRequest?: PutChangePasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putChangePassword(putChangePasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PutChangePasswordApi.putChangePassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PutChangePasswordApi - factory interface
 * @export
 */
export const PutChangePasswordApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PutChangePasswordApiFp(configuration)
    return {
        /**
         * 
         * @summary change password
         * @param {PutChangePasswordRequest} [putChangePasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putChangePassword(putChangePasswordRequest?: PutChangePasswordRequest, options?: any): AxiosPromise<void> {
            return localVarFp.putChangePassword(putChangePasswordRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PutChangePasswordApi - object-oriented interface
 * @export
 * @class PutChangePasswordApi
 * @extends {BaseAPI}
 */
export class PutChangePasswordApi extends BaseAPI {
    /**
     * 
     * @summary change password
     * @param {PutChangePasswordRequest} [putChangePasswordRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PutChangePasswordApi
     */
    public putChangePassword(putChangePasswordRequest?: PutChangePasswordRequest, options?: RawAxiosRequestConfig) {
        return PutChangePasswordApiFp(this.configuration).putChangePassword(putChangePasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PutStatusApi - axios parameter creator
 * @export
 */
export const PutStatusApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary update status
         * @param {Status} status request body of update status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putStatus: async (status: Status, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'status' is not null or undefined
            assertParamExists('putStatus', 'status', status)
            const localVarPath = `/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(status, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PutStatusApi - functional programming interface
 * @export
 */
export const PutStatusApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PutStatusApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary update status
         * @param {Status} status request body of update status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putStatus(status: Status, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Status>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putStatus(status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PutStatusApi.putStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PutStatusApi - factory interface
 * @export
 */
export const PutStatusApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PutStatusApiFp(configuration)
    return {
        /**
         * 
         * @summary update status
         * @param {Status} status request body of update status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putStatus(status: Status, options?: any): AxiosPromise<Status> {
            return localVarFp.putStatus(status, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PutStatusApi - object-oriented interface
 * @export
 * @class PutStatusApi
 * @extends {BaseAPI}
 */
export class PutStatusApi extends BaseAPI {
    /**
     * 
     * @summary update status
     * @param {Status} status request body of update status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PutStatusApi
     */
    public putStatus(status: Status, options?: RawAxiosRequestConfig) {
        return PutStatusApiFp(this.configuration).putStatus(status, options).then((request) => request(this.axios, this.basePath));
    }
}



