name: Deploy to Rental Server

on:
  push:
    branches:
      - hotfix/status
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create .env.prod file
        run: |
          cat << EOF > .env.prod
          ENV_TYPE="prod"
          MYSQL_HOSTNAME=${{ secrets.MYSQL_HOSTNAME }}
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          TZ="Asia/Tokyo"
          BACKEND_ENDPOINT="https://www.isdl-sentinel.com/v1"
          GOOGLE_CREDENTIALS_PATH="/go/src/app/internal/infrastructures/credentials"
          GOOGLE_DRIVE_FOLDER_ID=${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          WEBHOOKURL=${{ secrets.WEBHOOKURL }}
          SERVER_HOST=${{ secrets.SERVER_HOST }}
          LAB_NETWORK_IP=${{ secrets.LAB_NETWORK_IP }}
          EOF

      - name: Copy .env.prod file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ".env.prod"
          target: "~/ISDL-Sentinel/"
      
      - name: Create Google credentials files
        run: |
          mkdir -p ./backend/internal/infrastructures/credentials

          echo "${{ secrets.GOOGLE_CALENDAR_CREDENTIALS_JSON_BASE64 }}" | base64 -d > ./backend/internal/infrastructures/credentials/google_calendar_credentials.json
          echo "${{ secrets.GOOGLE_CALENDAR_TOKEN_JSON_BASE64 }}" | base64 -d > ./backend/internal/infrastructures/credentials/google_calendar_token.json
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS_JSON_BASE64 }}" | base64 -d > ./backend/internal/infrastructures/credentials/google_drive_credentials.json
          echo "${{ secrets.GOOGLE_DRIVE_TOKEN_JSON_BASE64 }}" | base64 -d > ./backend/internal/infrastructures/credentials/google_drive_token.json

      - name: Copy Google credentials files to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./backend/internal/infrastructures/credentials/google_*"
          target: "~/ISDL-Sentinel/"

      - name: Decode the SSL certificate
        run: |
          mkdir -p ./proxy/ssl
          echo "${{ secrets.SSL_CERT_PEM_BASE64 }}" | base64 -d > ./proxy/ssl/www.isdl-sentinel.com.pem
          echo "${{ secrets.SSL_CERT_NOPASS_KEY_BASE64 }}" | base64 -d > ./proxy/ssl/www.isdl-sentinel.com.nopass.key

      - name: Copy SSL files to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./proxy/ssl/*"
          target: "~/ISDL-Sentinel/"

      - name: Deploy to rental server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            cd ~/ISDL-Sentinel
            git pull origin hotfix/status
            make down prod
            make build-up prod
